"""Initial migration

Revision ID: 3c31ee0e6776
Revises:
Create Date: 2026-06-27 20:36:12.356466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c31ee0e6776"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anime_list",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("name_anime", sa.String(), nullable=False),
        sa.Column("create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("login", sa.String(length=20), nullable=False),
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("registered_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_account_email_address"), "user_account", ["email_address"], unique=True
    )
    op.create_table(
        "user_anime_list",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("anime_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WATCHING", "WATCHED", "PLANNED", "DROPPED", name="watchstatus"),
            nullable=False,
        ),
        sa.Column("create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["anime_id"], ["anime_list.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_anime_list")
    op.drop_index(op.f("ix_user_account_email_address"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_table("anime_list")
    # ### end Alembic commands ###
